### ISSUE TITLE
Missing file in the 'web' folder

### ISSUE THREAD

**Issue by alexgleith** [minus34/census-loader#5]
The server.py file in the web folder imports 'utils'. I don't think this is the same utils.py that is in the root of the project, and if it isn't, then this file is missing.

Can you please add it or let me know what I'm mising/!

**Comment by minus34** [comment]
It's badly located in the main folder as it serves both the DB build and the map server  Need to come up with a better solution to this.

**Comment by alexgleith** [comment]
Ok, I'll need to look into it a bit more, as I copied it into the web folder and still couldn't start the app. I'll get back to you =).

**Comment by alexgleith** [comment]
Hey @minus34 

Running server.py while importing utils wants to be run with the arguments. See below. I'll look at fixing this. I'm having other troubles importing geography using the docker process, and I'll try to put together a PR fixing this.

```
python3 server.py 
usage: server.py [-h] [--max-processes MAX_PROCESSES] [--pghost PGHOST]
                 [--pgport PGPORT] [--pgdb PGDB] [--pguser PGUSER]
                 [--pgpassword PGPASSWORD] [--census-year CENSUS_YEAR]
                 [--data-schema DATA_SCHEMA]
                 [--boundary-schema BOUNDARY_SCHEMA] [--web-schema WEB_SCHEMA]
                 [--num-classes NUM_CLASSES] --census-data-path
                 CENSUS_DATA_PATH --census-bdys-path CENSUS_BDYS_PATH
server.py: error: the following arguments are required: --census-data-path, --census-bdys-path
```

**Comment by minus34** [comment]
Yep, that is goofy!

**Comment by minus34** [comment]
Need to split the load-census only utils from the common utils

**Comment by alexgleith** [comment]
Closing this.
